CrudNetCore5/Models/ErrorViewModel.cs
using System;

namespace CrudNetCore5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNetCore5/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetCore5.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El título es obligatorio.")]
        [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Título")]

        public string Titulo { get; set; }

        [Required(ErrorMessage = "La descripción es obligatoria.")]
        [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "La fecha es obligatoria.")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha Lanzamiento")]

        public DateTime FechaLanzamiento { get; set; }

        [Required(ErrorMessage = "El autor es obligatorio.")]

        public string Autor { get; set; }

        [Required(ErrorMessage = "El precio es obligatorio.")]

        public int Precio { get; set; }
    }
}

CrudNetCore5/Controllers/HomeController.cs
using CrudNetCore5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetCore5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNetCore5/Controllers/LibrosController.cs
using CrudNetCore5.Data;
using CrudNetCore5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetCore5.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }
        //http get index
        public IActionResult Index()
        {
            IEnumerable<Libro> listLibros = _context.Libro;
            return View(listLibros);
        }
        //http get create
        public IActionResult Create()
        {
            return View();
        }
        //http post create
        [HttpPost]
        [ValidateAntiForgeryToken] //protección para los formularios para que un bot mande Muchos registros
        public IActionResult Create(Libro libro)
        {
            if (ModelState.IsValid) //crear registro de libro
            {
                _context.Libro.Add(libro);
                _context.SaveChanges();

                TempData["mensaje"] = "El libro se ha creado correctamente.";
                return RedirectToAction("Index");
            }
            return View();
        }
        //http get Edit
        public IActionResult Edit(int? id)
        {
            //si No entra aquí el id está seteado y sí existe el id
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Obtener el libro
            var libro = _context.Libro.Find(id);

            //si No se encuentra un libro con ese id
            if (libro == null)
            {
                return NotFound();
            }

            //si existe retorna el libro
            return View(libro);
        }
        //http post edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid) //crear registro de libro
            {
                _context.Libro.Update(libro);
                _context.SaveChanges();

                TempData["mensaje"] = "El libro se ha actualizado correctamente.";
                return RedirectToAction("Index");
            }
            return View();
        }
        //http get Delete
        public IActionResult Delete(int? id)
        {
            //si No entra aquí el id está seteado y sí existe el id
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Obtener el libro
            var libro = _context.Libro.Find(id);

            //si No se encuentra un libro con ese id
            if (libro == null)
            {
                return NotFound();
            }

            //si existe retorna el libro
            return View(libro);
        }
        //http post delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLibro(int? id) //recibe un entero que puede ser Nulo
        {
            //Obtener el libro por id
            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }
            
            _context.Libro.Remove(libro);
            _context.SaveChanges();

            TempData["mensaje"] = "El libro se ha eliminado correctamente.";
            return RedirectToAction("Index");

        }
    }
}

CrudNetCore5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudNetCore5/Views/Libros/Create.cshtml
@model CrudNetCore5.Models.Libro
@{
    ViewData["Title"] = "Crear nuevo libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear nuevo libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10"> <!--ocupa 10 columnas de las 12-->
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial"/>}
}

CrudNetCore5/Views/Libros/Delete.cshtml
@model CrudNetCore5.Models.Libro
@{
    ViewData["Title"] = "Eliminar libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10"> <!--ocupa 10 columnas de las 12-->
            <form method="post" asp-action="DeleteLibro">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" disabled/>
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" disabled/>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" disabled/>
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" disabled/>
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" disabled/>
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial"/>}
}

CrudNetCore5/Views/Libros/Edit.cshtml
@model CrudNetCore5.Models.Libro
@{
    ViewData["Title"] = "Editar libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10"> <!--ocupa 10 columnas de las 12-->
            <form method="post" asp-action="Edit">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial"/>}
}

CrudNetCore5/Views/Libros/Index.cshtml
@model IEnumerable<CrudNetCore5.Models.Libro>
@{
    ViewData["Title"] = "Lista de libros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="containter">

    @if (TempData["mensaje"] != null)
            {
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    @TempData["mensaje"]
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }

    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros">Agregar nuevo libro</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                        <td>@Html.DisplayNameFor(m => m.Titulo)</td>
                        <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                        <td>@Html.DisplayNameFor(m => m.FechaLanzamiento)</td>
                        <td>@Html.DisplayNameFor(m => m.Autor)</td>
                        <td>@Html.DisplayNameFor(m => m.Precio)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Titulo</td>
                            <td>@item.Descripcion</td>
                            <td>@item.FechaLanzamiento</td>
                            <td>@item.Autor</td>
                            <td>@item.Precio</td>
                            <td>
                                <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>

                                <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>
</div>

CrudNetCore5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNetCore5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudNetCore5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Crud Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CrudNetCore5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>